name: Build and deploy slides

on:
  push:
    branches:
      - main

jobs:
  build-slides:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_ARGS: "--no-sandbox"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          which convert  # Debug: Verify that 'convert' is available

      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libgtk-3-0

      - name: Install reveal-md
        run: npm i -g reveal-md

      - name: Build slides
        run: make build

      - name: Deploy slides
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_dir: ./_site/
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
          disable_nojekyll: false

